[package]
name = "aurion-indexer"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
aurion-primitives = { path = "../aurion-primitives" }
aurion-core = { path = "../aurion-core" }
rusqlite = { version = "0.31", features = ["bundled"] }
tokio = { version = "1.38", features = ["full"] }
thiserror = "1.0"
