[workspace]
resolver = "2"
members = [
    "crates/aurion-primitives",
    "crates/aurion-core",
    "crates/aurion-consensus",
    "crates/aurion-script",
    "crates/aurion-eutxo",
    "crates/aurion-storage",
    "crates/aurion-network",
    "crates/aurion-node",
    "crates/aurion-rpc",
    "crates/aurion-indexer",
    "bin/aurion",
]
default-members = ["bin/aurion"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Aurion Sovereign Core Contributors"]
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
float_arithmetic = "deny"
arithmetic_side_effects = "deny"
unwrap_used = "warn"
expect_used = "warn"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
