[package]
name = "aurion-rpc"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
aurion-primitives = { path = "../aurion-primitives" }
aurion-core = { path = "../aurion-core" }
async-trait = "0.1"
thiserror = "1.0"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt"] }
tracing = "0.1"